name       : apache-ant
version    : 1.10.9
release    : 8
source     :
    - https://github.com/apache/ant/archive/rel/1.10.9.tar.gz : dbd058de445aa80d46afdcc0bff0dce9a0a8f85a744e718e31b9700669f126fd
license    : Apache-2.0
component  : programming.java
summary    : A software tool for automating software build processes
description: |
    Apache Ant is a Java library and command-line tool whose mission is to drive processes described in build files as targets and extension points dependent upon each other.
builddeps  :
    - openjdk-11
rundeps    :
    - openjdk-11
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    ./build.sh -Dant.install=$installdir/usr install-lite
install    : |
    find $installdir/usr/bin \( -name '*.cmd' -o -name '*.bat' \) -delete
    mv $installdir/usr/lib $installdir/usr/lib64

    cd $installdir/usr/bin
    find . -type f \! -name "*.*" -exec sed --debug -i "2r $pkgfiles/java-shim.txt" {} \;
