name       : apache-ant
version    : 1.10.11
release    : 10
source     :
    - https://github.com/apache/ant/archive/refs/tags/rel/1.10.11.tar.gz : 55a5afe0d40449667162b1cdc6478bc1d99370ddcbb63d708913921fa22b6232
license    : Apache-2.0
component  : programming.java
homepage   : https://ant.apache.org/
summary    : A software tool for automating software build processes
description: |
    Apache Ant is a Java library and command-line tool whose mission is to drive processes described in build files as targets and extension points dependent upon each other.
builddeps  :
    - openjdk-11
rundeps    :
    - openjdk-11
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    ./build.sh -Dant.install=$installdir/usr install-lite
install    : |
    find $installdir/usr/bin \( -name '*.cmd' -o -name '*.bat' \) -delete
    mv $installdir/usr/lib $installdir/usr/lib64

    cd $installdir/usr/bin
    find . -type f \! -name "*.*" -exec sed --debug -i "2r $pkgfiles/java-shim.txt" {} \;
