name       : apache-ant
version    : 1.9.7
release    : 5
source     :
    - http://supergsego.com/apache//ant/source/apache-ant-1.9.7-src.tar.gz : 648b3f3787bb0cb6226978b6d4898eb7e21ae391385357a5f824972dd910a1c8
license    : Apache-2.0
component  : programming.java
summary    : Apache Ant is a Java library and command-line tool that help building software
description: |
    Apache Ant is a Java library and command-line tool whose mission is to 
    drive processes described in build files as targets and extension 
    points dependent upon each other.
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-8/
    mkdir build_ant
    ./build.sh -Ddist.dir=build_ant dist 
install    : |
    mkdir -p $installdir/usr/bin $installdir/usr/lib64
    install -m 755 %workdir%/build_ant/bin/* $installdir/usr/bin
    install -m 755 %workdir%/build_ant/lib/* $installdir/usr/lib64
    rm -rf $installdir/usr/lib64/README build_ant
