name       : apache-ant
version    : 1.10.7
release    : 6
source     :
    - https://github.com/apache/ant/archive/rel/1.10.7.tar.gz : 76847cb016937266872b5f83bd5a6dc3587b9df6a6545f57213f79358c16457a
license    : Apache-2.0
component  : programming.java
summary    : A software tool for automating software build processes
description: |
    Apache Ant is a Java library and command-line tool whose mission is to drive processes described in build files as targets and extension points dependent upon each other.
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-to-using-openjdk-8.patch
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-8
    ./build.sh -Dant.install=$installdir/usr install-lite
install    : |
    mv $installdir/usr/lib $installdir/usr/lib64
    find $installdir/usr/bin \( -name '*.cmd' -o -name '*.bat' \) -delete
